apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    ingress:
      # Route to a frontend service
      - hostname: chat.orasuno.pl
        service: http://mattermost.mattermost.cluster.local:8065

      # Required catch-all rule (must be last)
      - service: http_status:404