apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaku-whoami
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app1/out
    repoURL: https://gitlab.com/homelab-dev/2-talos-os.git
    targetRevision: argo
  syncPolicy:
    automated:
      selfHeal: true
