---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mattermost-postgres-secret
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_CHECK_URL: AgDJN8GhbtWSrJpWn06N33dUVm9nB9+eEzasdNJ9sB0hTglL6j6tpTZKD8DzB+exBOvbZ4MFOYgfZYWTPWR9EnkxDM1KH3MOr+9a8HcW20kKMdOj54MR2D7uv3CLIPAK7PckVTo0Q2RkKyd1bwrx8NpYC05uWoiQUz3UzEDUZwICSuxmCWX4uht1bM1Hgu/E6BUYXmrJGFuATdEsSHWl30r2A6EiafQiHos7gX7A/cOr9hn+lOyHGBvqSJn9i5ilhGpRaoWsaDWEvN5M3RYAV1N3kC1kT91dABtHdTq9osCeyreiy+xdO5nVyEuKKbBvjYCV03HZMXHv4591O67sZ632tAQlVqab5ZD4hcTE77m+gLrLtYu8CcBuuvpTX9phvWwLljiOVDV5FMZzWQMNb9UFnUH8/mhBbgR8oLNCLDCyGWqvMoshltsF1bZ7RH8iEhdd9PI8IIRGD1GEVz6DHmCw6pexEHag0wmql4A6jQedd3gJyp+yQnE6N+kV+B51H945k2uzoIFaqfZw9u+oEiz+HeqRRF2CVEbaZ5Pac2XamDBPR5G3tZMAlPkK4fAeA34HQIgbWgRk9RclXWhGupTTgk0KjQB4OifKjsMVKjeYRA/MrpuxFPngBSRVyxbiKXMv+hYwEGpbdIdM6T7G6HSytzN08nadjS6GgDtKLfakHFyU0xmw7gnju0J+BMxXHDJW5P6hb0lZi8s1OKv87P1wdhBep4C3HKOHCOcSDkFhWtzvTtUUbM5HW38FPwWZra6+Q03lwFLZdYn6fSfKQlgi7temaR8sXB/G8YJgCspFogrfp+OM8/BNXl5i+flIfsiX3ZLyKz/1lTwRe0UHPK6+22N4z0d6ywqJe4UaNLxPxD2G6XxgIsKXRxZvquLWVASfnSdLAobgCIZ3YdjTplljmf2VeVC6Tn/6DfQ=
    DB_CONNECTION_STRING: AgDJN8GhbtWSrJpWn06N33dUVm9nB9+eEzasdNJ9sB0hTglL6j6tpTZKD8DzB+exBOvbZ4MFOYgfZYWTPWR9EnkxDM1KH3MOr+9a8HcW20kKMdOj54MR2D7uv3CLIPAK7PckVTo0Q2RkKyd1bwrx8NpYC05uWoiQUz3UzEDUZwICSuxmCWX4uht1bM1Hgu/E6BUYXmrJGFuATdEsSHWl30r2A6EiafQiHos7gX7A/cOr9hn+lOyHGBvqSJn9i5ilhGpRaoWsaDWEvN5M3RYAV1N3kC1kT91dABtHdTq9osCeyreiy+xdO5nVyEuKKbBvjYCV03HZMXHv4591O67sZ632tAQlVqab5ZD4hcTE77m+gLrLtYu8CcBuuvpTX9phvWwLljiOVDV5FMZzWQMNb9UFnUH8/mhBbgR8oLNCLDCyGWqvMoshltsF1bZ7RH8iEhdd9PI8IIRGD1GEVz6DHmCw6pexEHag0wmql4A6jQedd3gJyp+yQnE6N+kV+B51H945k2uzoIFaqfZw9u+oEiz+HeqRRF2CVEbaZ5Pac2XamDBPR5G3tZMAlPkK4fAeA34HQIgbWgRk9RclXWhGupTTgk0KjQB4OifKjsMVKjeYRA/MrpuxFPngBSRVyxbiKXMv+hYwEGpbdIdM6T7G6HSytzN08nadjS6GgDtKLfakHFyU0xmw7gnju0J+BMxXHDJW5P6hb0lZi8s1OKv87P1wdhBep4C3HKOHCOcSDkFhWtzvTtUUbM5HW38FPwWZra6+Q03lwFLZdYn6fSfKQlgi7temaR8sXB/G8YJgCspFogrfp+OM8/BNXl5i+flIfsiX3ZLyKz/1lTwRe0UHPK6+22N4z0d6ywqJe4UaNLxPxD2G6XxgIsKXRxZvquLWVASfnSdLAobgCIZ3YdjTplljmf2VeVC6Tn/6DfQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mattermost-postgres-secret
      namespace: mattermost
    type: Opaque
