---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mattermost-postgres-secret
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_CHECK_URL: AgBwuWyxfwjWTbpF+PnDaCLex0Ahguo+7CVfO+56O5ulkgO6EGkRYSAxqw4daWOkQmfvPaWW7IjKjoWh15CJOJvEJ+2B0ovXArH+2NzA/knHmAma73JjFxszyQqe666q6s/QK2U+4ttBlGuzYI5E8TxKZud0w2fn2SK9fUaB2hwM/axeLmxEW4J9SMRJA9ZvTcIZZtXvx9ftEjkt0ocQCTix+G5RLnr8vzkS6GvpK89gGZ4eyfLyvzholBnlb/xsfBIHSGrW0THF9eOv2ZawiKHxhSEJ2VUAEYHSaTTs5s9OyIF7gwty5jqO1UxOiXR+/Ht0X1oMGPPxN+DJutjrHtCTpLi69LvDdKmXrjjWZ0U8ZymPZA+7XBNZbYnNHhPyKKH+WrAvM2Yy1oG7/6U955lD2btwwZyNlgLe2qTkye4hnNW61KVY52Ehsl/Igl4YsOqjrYdRzuwEFwI5r3HhpRCMuwcSKikT4EU2W54zs8HUS/HPHIBXnfvlr3dE1DuIs1Q4Ywng75cOFUvUHNN4tTDVE1B+oA+p8gDJeeUsBCNjGAQUHu1LbKO0NF8CRadR9ZJJkICWZl2vTjvKIdytY06J2zD/l7cgG6U/QOP2MfV7Xw3AGS0I8pKIFo6hyHLdl6yyRQHTqjXlIl3HP/pDXMoqgo4ApGcNC8kLCrWG0OBBiDngvfGzxSme9f4FasZCoWkmHOxSCS1gFUspR59n3o03IwLeDlPfQno5Bj3nc9jqX/OM8Wu0HGfDlrxrpOpYxexBa2NcQNHQldYaRYei9bK2+BnFXx138iMNiqrh3MRTY2rbeUCOeY4dY4Fjx3Q+ooj7ZxXT0+S+weGELdW29UZO7IYB+2tj2/BcMqKcrDsqKzcfcnJ8ARG6M1fXCMfnrJFfc+Rx1Qwvh/NhzZbLM/fBCIesKk0ZIimyDKE=
    DB_CONNECTION_STRING: AgAbgJIYkNw5vSwsYPbOXOjBiR3iAcq2KW9uyRMaoKexV5rE3MobtBcEISWw07gXhMhjJ0oNjLJ+vy34N+D/2N1p1CRXVtWVTE+gSI/qSzE7Ezk03fQoMdYYv6g1VzEpIbziWYxMxpT711sR4KMmmYH6ov2I7rgmFk0E4gfh6Zkf0+Ia7KHzfH4vy9+/THC6j//tDNigZUfeu5W1i7MnZYIr1cAY/LnmPrA4G6U+W0ZRrxKDHxt3R3uJV87lbmLsmD2G/1JBmmjFDGKoy/Ekz6vlKdSNy4hQKLcpxh8uo1V6XZBUUjifpN5ooq8QieUBnWMLDkL90qUKlN5fwxAhGAIsNk6YmXSfpS9vy8GXMrgmwmKMRrcKNBl2a5iR7O/Pvc2mmt+h459Fs76Ky+l/XzE2DzNlyPf3uggPbABjqpYVrtGmiBv3E7VI+0TKlX7EIZ6Hb44rMwwGHC5rVZqS88KgXPSCabtt4toq24BAgrO8UvAld3ZVFhRqiXWYEhRcjxhPRDI9/a/aRJgtjtMxVhAWmNjFRpZxTcCBTIH+E3IYFeb9LIXJC+AYEx1FbUj0ZCneQGURa7QWS9Qkyjz5/EGLlyy93R+Eb9inlJCEFWLkSsnqO+w2339SHfF8pTIqvWNUKVmJFuTy6mNCIEhumljXbeC1W7CGJWfUc8T+r/1UTOk9r7ueN1gHRg0DciW2kjlMGknqsSisipnHXmTiwktKYKdQAKp43h2LXxttY+MbdZoBN3rySPuajWcKiI9CLhqhLY3W4qMlg10/Xz+NPiqv7LtiOeLtaRKJtSX1wPuSlN+ldsK+zrcQWiHp+CsrwnAnZspeTuS9V3tuSYb1WpUQ9DHTadjy/HX+/BWhQPikO34FRDNzSiCmeDFsloS5BSa+JWGFJ6X36s9WQfqMvoH3DWwbwvxCT9QUrzE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mattermost-postgres-secret
      namespace: mattermost
    type: Opaque
