apiVersion: v1
kind: Secret
metadata:
  name: ente-credentials
  namespace: ente
type: Opaque
stringData:
  credentials.yaml: |
    s3:
      primary:
        key: "REMOVED_S3_KEY"
        secret: "REMOVED_S3_SECRET"
      derived:
        key: "CHANGE_ME_MINIO_ACCESS_KEY"
        secret: "CHANGE_ME_MINIO_SECRET_KEY"
    encryption:
      key: ""
      hash: ""
    jwt:
      secret: ""
    smtp:
      enabled: false
    stripe:
      enabled: false
