apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kuma-mesh
  namespace: flux-system
spec:
  interval: 10m
  path: ./03-flux-apps/19.kuma-mesh
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
