apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akna-one-pl
  namespace: gateway-api
spec:
  secretName: akna-one-pl-tls
  issuerRef:
    name: desec-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.akna.one.pl"
