apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diagnostic-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    #chart: diagnostic-appk
    repoURL: https://gitlab.com/homelab-dev/2-Apps.git
    path: sources/charts/diagnostic-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
