---
# Service Configuration Object
apiVersion: v1
kind: ConfigMap
metadata:
  name: mattermost-service-config
  namespace: mattermost
data:
  service.type: "ClusterIP"
  service.port: "8065"
  site.url: "https://chat.orasuno.pl"
  websocket.url: "wss://chat.orasuno.pl"
  site.name: "Family Mattermost"
  company.name: "Akna Family"
