---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ente-s3-backup
  namespace: ente
spec:
  encryptedData:
    accessKeyId: AgAotMlkKXonKHDwfeATAbxbnfWg+JI+puSGt/trpfnbQFIp/+ol5PBfULOIQ/zn7jwz7e9EFkWv24YvJiRjIK/kW278KyzuCUbWwA/qXgMMEMfgCInTAFBU90v52+w0fFgCfatvdHyeQSL2vn7DD19GVz79VrTYcOosZYu7KCwfJI/vyIb4jkR+WCoZgSeRPKSFlFfnd4nKiYLfiC59ptlRJrtDPsFcKqyRxMlKsQs+h+xX+Ms7GtBjaG6EEmEJWFS0jXeTdBK23ZROgq7ilbPo+RXARl/D8gib8WgSHOMHS9vP+Q1fYM5AyOS9UeYntyaDINllXEwgTkdNcFUUUVFPoobh5EJVmaNDnbYSHCSxKYrOUnmU0iX6v7/KZIg37MKiGHrjieCX7wrXzOyMUVVBGwvtNf+UrUu5Xk0fY4VoDs6UQ9dIDlJLF6eWwJeQMdYC8Pjm6dbSPQBciY+r922D3KYmCurlB1DBS2/KP0vpoIHVKC2RoY9xfwN1WA9jd6w7M8mG8ukxQT63txno3AaeedMOa/52FqmbjrlO4JRWfs1rbgr2/XHNjPycc3/pwLCOKd5jritN+KJRZqDVV/DECw0vk/BghcxK04IJOJ6KbXo0hsThZcFOEosfslbNV1DjXbOcXTA58X05zJXX82EDx3GOPgKryRyr5/IZVmOgn6qVQ3YNY/sokjF+goyZ4/gqhTVsLXdGQI/b2aiM0GUns2hH/g==
    secretAccessKey: AgASqM8twuiQvuIzC46vzGr+3jBRO8+iFhI6t9jj5mkGQqhD3wbi+xZgRvq6iOvsnATdFU+OMQusgcdsc1r3AvWYj3AjItSil9wNrBKNtm49ipozq/HxJY0uNbPSf/IuTfcW1B56QAE6/0qkNfe0tcv72yz5R5hJjQNZ24Uvnc/eD7FiIS2t9VUOLzrk+XvaYLFTxwPQvgnQqmucn4QiMLemI7V4XIM3gmTFXAweJSPrWBtJpxi9YN8nNhPsvGvpN/siKqP+yWlCrn24fofRSruvSBOst2io+I2MicdwwiG3y6NHdN0Aabu6QmPNDx3edNP6RRkdEMWvDk5dfDwBP306K01E+JPdSyLMyM+2hxWf/tewYHv7vDtrHhBFL+sNUAoTCVbTRC3Sed+/d+osy6qPQ921j+ATXieRaAoqlYyiOMoYxrPWtHHE8l4h3AHutyuBufQy8BL3q7BrRQb8Pj6fkgCoPWq2Lrwho4yTa1nSFo2lCal1xCDdfIwZNASIPZ/kNEOU8QBw9D4WuNGwDmLWJTftUeQqql5jPfAs7UwV07OmArauS87s8i9L9i4KLBGAKifrojfc4XqKH2JYRXV+qaxc2oraKY2o4d5aduZWJit1tC0HC1GT5n9Bf51K2F8Sd1CzS2KWrlXXEgwYCsp6XFzMPtc9NJiVELmqmAA0CSLYybozVfADgf1ITAD7mCFSHkhyFSJDyFq9iAd2ffj64ZuTC3yup9YMpGWx9oecr55A2dLBhTPl21s=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ente-s3-backup
      namespace: ente
    type: Opaque
