apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |
    {
      "nodePathMap":[
        {
          "node":"NODE_NAME",
          "paths":["/var/local-path-provisioner"]
        }
      ]
    }
---
# Annotate each node:
# kubectl annotate node NODE_NAME local-path-provisioner.node.kubernetes.io/path=/var/local-path-provisioner
