apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beyla
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: beyla
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.4.0
    helm:
      releaseName: beyla
      valuesObject:
        beyla:
          configMap:
            content: |
              Prometheus:
                Metrics:
                  Enable: true
                  Path: "/metrics"
                  Port: 9090
              OpenTelemetry:
                Traces:
                  Enable: true
                  Protocol: "grpc"
                  Endpoint: "alloy.alloy.svc:4317"
              Service:
                AutoDiscover:
                  - namespace: ".*"
                    port: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
              - SYS_PTRACE
  destination:
    server: https://kubernetes.default.svc
    namespace: beyla
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
