apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
  namespace: rustfs
spec:
  interval: 5m

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: rustfs
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: rustfs
        namespace: flux-system
  values:
    mode:
      standalone:
        enabled: false
      distributed:
        enabled: true
    replicaCount: 4
    storageclass:
      name: local-path
    image:
      repository: rustfs/rustfs
      tag: "latest"
    secret:
      rustfs:
        access_key: rustfsadmin
        secret_key: rustfsadmin
    ingress:
      className: ""
      enabled: false
