apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.5.0
    helm:
      releaseName: alloy
      valuesObject:
        configMap:
          create: true
        alloy:
          configMap:
            content: |
              logging {
                level = "info"
              }

              # CNPG scrape
              # scrape {
                     job_name = "cloudnativepg"
                     namespace = "default"
                     selector {
                                matchLabels = { "cnpg.io/cluster" = "test-cluster" }
                              }
                      metrics_path = "/metrics"
                      port = 9187
                      scrape_interval = "30s"
                      }

              remote_write {
                url = "http://vmsingle-vm.victoriametrics.svc.cluster.local:8429/api/v1/write"
              }

        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
