apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.18.5"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  hubble:
    enabled: true
    metrics:
      enabled:
        - dns
        - drop
        - tcp
        - flow
        - icmp
        - http
    relay:
      enabled: true
    ui:
      enabled: true
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ipam:
      mode: kubernetes

    gatewayAPI:
      enabled: true

    envoy:
      enabled: true

    kubeProxyReplacement: true

    bgpControlPlane:
      enabled: true

    k8sServiceHost: localhost
    k8sServicePort: 7445

    bgp:
      enabled: true

    bpf:
      masquerade: true

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
