upgrade:
  helm upgrade cilium cilium/cilium --namespace kube-system --version 1.18.5 -f values.yaml
install:
  helm repo add cilium https://helm.cilium.io/ ; helm repo update;
  helm install cilium cilium/cilium --namespace kube-system --version 1.18.5 -f values.yaml
