apiVersion: v1
kind: Service
metadata:
  labels:
    app: netshoot1
    advertise: lb
  name: netshoot1
  namespace: default
spec:
  ports:
    - nodePort: 32649
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: netshoot1
  type: LoadBalancer
  loadBalancerIP: 10.40.0.150
