apiVersion: v1
kind: Pod
metadata:
  name: netshoot-debug
  namespace: tempo
spec:
  restartPolicy: Never
  containers:
  - name: netshoot
    image: nicolaka/netshoot:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
    volumeMounts:
      - name: tempo-storage
        mountPath: /mnt/storage-tempo-0
  volumes:
    - name: tempo-storage
      persistentVolumeClaim:
        claimName: storage-tempo-0
