apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-fs-pvc
spec:
  storageClassName: zfs-iscsi-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
