apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-example
  namespace: default
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: homelab-secretstore
    kind: ClusterSecretStore

  target:
    name: openbao-example
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: username
      remoteRef:
        key: lab/example
        property: username

    - secretKey: password
      remoteRef:
        key: lab/example
        property: password
