# Talhelper - confoguration file
---
clusterName: ${ClusterName}
talosVersion: v1.12.4
kubernetesVersion: v1.34.0
endpoint: https://10.30.0.200:6443
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - 10.30.0.200
  - ${ClusterName}
additionalApiServerCertSans:
  - ${ClusterName}
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
patches:
  - "@./patches/machine/enable-discovery-patch.yaml"
  - "@./patches/machine/kernel-modules.yaml"
nodes:
  - hostname: cp-node01
    ipAddress: 10.30.0.29
    controlPlane: true
    nodeLabels:
      bgp: "true"
    installDisk: /dev/vda
    patches:
      - "@./patches/nodes/cp-node01-volume.yaml"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/amd-ucode
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 52:54:00:12:34:30
        addresses:
          - 10.30.0.29/16
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.30.0.1
        vip:
          ip: 10.30.0.200
      - deviceSelector:
          hardwareAddr: 52:54:00:12:34:40
        addresses:
          - 10.40.0.29/16
        mtu: 1500
  - hostname: cp-node02
    ipAddress: 10.30.0.31
    controlPlane: true
    nodeLabels:
      bgp: "true"
    installDisk: /dev/vda
    patches:
      - "@./patches/nodes/cp-node02-volume.yaml"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/amd-ucode
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 06:54:00:12:34:30
        addresses:
          - 10.30.0.31/16
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.30.0.1
        vip:
          ip: 10.30.0.200
      - deviceSelector:
          hardwareAddr: 06:54:00:12:34:40
        addresses:
          - 10.40.0.31/16
        mtu: 1500
  - hostname: cp-node03
    ipAddress: 10.30.0.32
    controlPlane: true
    nodeLabels:
      bgp: "true"
    installDisk: /dev/vda
    patches:
      - "@./patches/nodes/cp-node03-volume.yaml"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/intel-ucode
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 32:54:00:12:34:30
        addresses:
          - 10.30.0.32/16
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.30.0.1
        vip:
          ip: 10.30.0.200
      - deviceSelector:
          hardwareAddr: 32:54:00:12:34:40
        addresses:
          - 10.40.0.32/16
        mtu: 1500
  - hostname: w-node04
    ipAddress: 10.30.0.33
    controlPlane: false
    nodeLabels:
      bgp: "true"
    installDisk: /dev/vda
    patches:
      - "@./patches/nodes/w-node04-volume.yaml"
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/qemu-guest-agent
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
            - siderolabs/intel-ucode
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: 44:54:00:12:34:30
        addresses:
          - 10.30.0.33/16
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.30.0.1
      - deviceSelector:
          hardwareAddr: 44:54:00:12:34:40
        addresses:
          - 10.40.0.33/16
        mtu: 1500
controlPlane:
  patches:
    - "@./patches/machine/cluster-proxy-disabled.yaml"
