apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "9.4.15"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    applicationSet:
      enabled: true
    configs:
      cm:
        url: https://argocd.akna.one.pl
    server:  
      # Allow HTTP (port 80) without redirect to HTTPS
      insecure: false
