apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-example
  namespace: default
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: lab/example
      metadataPolicy: None
      property: username
    secretKey: username
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: lab/example
      metadataPolicy: None
      property: password
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab-secretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: openbao-example
