---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acme-dns
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgCTV/Itjlw1KfiMsx/FBPCVZbs4IRcWlkON3T9IR0770cEIwpUfbl7OmdUQD69gSeqCGGvhVyr+1RXZHu5Dq7NTZBOq4nFpQSy5/9oPVVusY03+KcEc4l8icnzm14iRHpjWT7DtUQ87OLEa59CJ8JaHBx0OLEgo7DbJmzmGDQgpaFh1uXWAhtiGuowo7yQlYCxT0BJzX7BPxz/Ccb/b30IkuHPVy34uR6VyLZZ5e4SL50k14ed84DbWuRstiQyi3K3W1zZD+w98Pihj6azbs2Xx+YByNej67TFvepZakuU3jGcAJBH3AexOdCo1KLVuJvGYOIJ4ffhw+e98Y34VLqQ/5vf4xWdO5AxlM/LaNJOzpN2Kamr3M/ijxIqNCO8unzoBo6QVjluLAe2u9w2qmdwFS1+zxXSq5IEHXLcETuISLb9W2xa72iXta2nh7zxm+vSxHOwl9IFOQ+BDuGqA1blMDx0AUd7QSetpYSnBbM9s8LInEALGd7Jz5EEqDwKhWr3pCdNAURqMyhhzgqbuLBqoCRjxMX2OnwQY7h5pg9tbD2+3aOGAC4R+MYjAS3eG1Ud7LcUcg7Wfrhn0b1DKDUw7Nw64591cqsNiwTneVSBhCHl8XXc34rsqH1kHSekJGBHpqqQ7Z1y1d763woaJ16r2nNVH4PBb0GuaUlLVb8lEvKZmyRAthjNNhKJLZmBKXg53VKlOhieSaBAZF1Gb32MF0Gh+RPwmosJMOxc3/wSSeBjXfabzZkZLlWcSULs7s0GeOuvO/3YqHCjeUTOVrzeqDRyh43aiIZoH0QTXGyr7DNAgfUux2fK2K22KqsGJhAWFitlz08WBge59NpMcr44PNQ2NjdT/evYRYhfUpvmJJv19dWYEFeQBj9pW9vZ14S3M7P6maeauPFVdrWKZM/XbZ6isgNikwTHHsr2fzPUalEFFkYrPeqvDghc5T8K2u1vCOYfcP5QX3cxWCBkTrYqx11uvZSPd7m79WJ7LjkynjWZ+UDRIx9OkpeaMv8m2tRb+1lePhY5xCLyvbA79SsT7b2mrYgE3YfzCIKboKl55ZsAQ2iAiUGu3P7/B7Lw=
  template:
    metadata:
      name: acme-dns
      namespace: cert-manager
