---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: desec-credentials
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgC5IMNKBbWOkPZBJaeq0oaCRF54lS2hNkif+i06bgIDfZTAydGINCYOuIiFF6YoRn/13tEOiUU1iJH/hisvSaLBOQwj0cllZ6s8/41xi3u+5BVHSCLLrS+5XikYbHjZZEnPUFnOvfmMdvPLt7b5lS9So9+qRtCVsGUEEr27ByIvo4eOSrlrFdnS7ktKERmSFsOX3ukawFWJJHjUpWo3sf8+CdEJeyhaz12ezU6SgAIABOHjufgDFqqvz0V91A5yBsr8ylFADIzB7he7CGLQU/4XH6pxt3WLlvn2DMPmi7nvZMqlDt+0l9Com2llG8g9qI7O39ZW6wByL82lTOHF72zLuYSJMpR9Y6kv06CoM0DHWPjch+XKSbQqWwqSVZsYK9SHsrMaMzbv2H+A+/Oyc0kq1X/ACO0cvj3nECpve+CmLEgg9viWdqp5UbuL97FsmIjvpO3y8k8kaBtVtu+sCAybe6SCL/SOsfrQVArXx5SbGFTfyMaIsrGmqzyFP2ePskGM1H7XsLhXYWTvTg+by1t2wAdpZZqH3JRPWwkz6HREQrkfE7Zeo1MO+SeaTdPTrA7IJXf+hr0ZQR2NQc4OeU8VT/Mhgu6n0BM3Zcy1coNuxE+pSZYibRy9lPitaYceKMAY9f0MltYBzDYYlzAo6L+NPxf4Wgl+q5UGAFBGaXo0yZ0ihBUMlkAIrWpZFdcxhdemwe9KjmvXAfRavvCIt7Kp7XLF5TOPZve6HfmQ
  template:
    metadata:
      name: desec-credentials
      namespace: external-dns
    type: Opaque
