apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-spiffe-csi
spec:
  background: false
  rules:
    - name: add-csi-volume
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  spiffe: "true"
      preconditions:
        all:
          - key: "{{ request.object.spec.volumes[].name || '' }}"
            operator: AnyNotIn
            value:
              - spiffe-socket
      mutate:
        patchesJson6902: |-
          - op: add
            path: /spec/volumes/-
            value:
              name: spiffe-socket
              csi:
                driver: csi.spiffe.io
                readOnly: true
    - name: add-csi-volume-mount
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  spiffe: "true"
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchesJson6902: |-
              - op: add
                path: "/spec/containers/{{ elementIndex }}/volumeMounts/-"
                value:
                  name: spiffe-socket
                  mountPath: /var/run/secrets/workload-spiffe-credentials
                  readOnly: true
