apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  interval: 5m

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: openbao
      version: "0.26.2"
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: flux-system

  values:
    global:
      enabled: true
      tlsDisable: false

    injector:
      enabled: false

    server:
      auditStorage:
        enabled: false
      extraEnvironmentVars:
        BAO_CACERT: /openbao/ca/ca.crt
      ha:
        enabled: true
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 0
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_cert_file = "/openbao/tls/tls.crt"
              tls_key_file = "/openbao/tls/tls.key"
              #tls_ca_file = "/openbao/ca/ca.crt"
            }
            storage "raft" {
              path = "/openbao/data"
              retry_join {
                leader_api_addr = "https://openbao-active:8200"
                leader_ca_cert_file = "/openbao/ca/ca.crt"
              }
            }
            service_registration "kubernetes" {}
      dataStorage:
        enabled: true
        size: 5Gi
      volumes:
        - name: tls
          secret:
            secretName: openbao-server-tls
        - name: ca
          secret:
            secretName: openbao-ca
      volumeMounts:
        - name: tls
          mountPath: /openbao/tls
          readOnly: true
        - name: ca
          mountPath: /openbao/ca
          readOnly: true

    ui:
      enabled: true
