apiVersion: api.kagent.dev/v1alpha3
kind: ModelConfig
metadata:
  name: openrouter
  namespace: kagent
spec:
  provider: OpenAI
  apiKeySecret: openrouter-api-key
  apiKeySecretKey: OPENROUTER-API-KEY
  model: qwen/qwen-2.5-7b-instruct
  openAI:
    baseUrl: "https://openrouter.ai"