apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: desec-issuer
spec:
  acme:
    email: fajrovulpo@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: desec-issuer-account-key
    solvers:
      - dns01:
          acmeDNS:
            host: https://auth.acme-dns.io
            accountSecretRef:
              name: acme-dns
              key: acmedns.json
#https://cert-manager.io/docs/configuration/acme/dns01/acme-dns/
