apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-desec
spec:
  acme:
    email: fajrovulpo@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.ukmetrics.ca
            solverName: desec
            config:
              apiTokenSecretRef:
                name: desec-api-token
                key: token
# https://github.com/kmorning/cert-manager-webhook-desec/tree/master/examples
