apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.5.0
    helm:
      releaseName: grafana
      valuesObject:
        replicas: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        persistence:
          enabled: true
          size: 10Gi
        sidecar:
          enabled: true
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
            folder: /var/lib/grafana/dashboards
            searchNamespace: ALL
          datasources:
            enabled: true
            label: grafana_datasource
            labelValue: "1"
            searchNamespace: ALL
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
