apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-kustomization.yaml
  - cert-manager-kustomization.yaml
  - cert-mamager-crds.yaml
  - external-secrets-kustomization.yaml
  - gapi-flux-kustomization.yaml
  - local-path-provisioner-kustomization.yaml
  - longhorn-kustomization.yaml
  - sealed-kustomization.yaml
  - kube-state-metrics.yaml
  - democratic-csi-kustomization.yaml
  - spiffe.yaml
  - external-dns.yaml
  - cilium.yaml
