apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-kustomization.yaml
- cert-manager-kustomization.yaml
- cert-mamager-crds.yaml
- csi-kustomization.yaml
- external-secrets-kustomization.yaml
- gapi-flux-kustomization.yaml
- local-path-provisioner-kustomization.yaml
- sealed-kustomization.yaml
