apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-kustomization.yaml
  - cert-manager-kustomization.yaml
  - cert-mamager-crds.yaml
  - external-secrets-kustomization.yaml
  - gapi-flux-kustomization.yaml
  - prometheus-kustomization.yaml
  #- local-path-provisioner-kustomization.yaml
  #- piraeus-kustomization.yaml
  - sealed-kustomization.yaml
  - kube-state-metrics.yaml
  - democratic-csi-kustomization.yaml
  - spiffe.yaml
  - external-dns.yaml
  - cilium.yaml
  - openebs-kustomization.yaml
  #- rustfs-kustomization.yaml
  #- garage-kustomization.yaml
  #- velero-kustomization.yaml
  #- kuma-mesh-kustomization.yaml
  - kyverno-kustomization.yaml
  - istio-ambient-kustomization.yaml
  - openbao-kustomization.yaml
  #- csi-secrets-kustomization.yaml
