apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cilium
  sourceRef:
    kind: Kustomization
    name: cluster-tools
  path: ./08.prometheus
  prune: true
  wait: true
  timeout: 5m
