apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 5m

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: ./charts/base
      version: "1.29.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    revision: "1-29-1"
