apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: ./charts/istio-control/istio-discovery
      version: "1.29.1"
  values:
    revision: "1-29-1"
    global:
      ambient:
        enabled: true
    pilot:
      configSource:
        enabled: true
