apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository-base.yaml
  - ocirepository-istiod.yaml
  - ocirepository-ztunnel.yaml
  - namespace.yaml
  - istio-base-helmrelease.yaml
  - istiod-helmrelease.yaml
  - ztunnel-helmrelease.yaml
