apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
  - kiali-helmrepo.yaml
  - namespace.yaml
  - kiali-namespace.yaml
  - istio-base-helmrelease.yaml
  - istiod-helmrelease.yaml
  - istio-cni-helmrelease.yaml
  - ztunnel-helmrelease.yaml
  - kiali-helmrelease.yaml
  - kiali-httproute.yaml
  - net-policy.yaml
