apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  interval: 5m

  install:
    createNamespace: true

  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: ztunnel
      version: "1.29.1"
      sourceRef:
        kind: OCIRepository
        name: istio-ztunnel
        namespace: flux-system
  values:
    revision: "1-29-1"
