apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ente
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://l4gdev.github.io/helm-charts
    chart: ente-photos
    targetRevision: 0.2.0
    helm:
      releaseName: ente
      valuesObject:
        museum:
          config:
            jobs:
              cron:
                skip: true
        credentials:
          #existingSecret: "ente-credentials"
          s3:
            b2-eu-cen:
              #primaryBucketName: "ente-photos"
              primary:
                endpoint: "http://10.10.0.77:8333"
                region: "us-east-1"
                bucket: "ente"
                key: "REMOVED_S3_KEY"
                secret: "REMOVED_S3_SECRET"
        externalDatabase:
          host: "ente-postgres-rw.ente.svc.cluster.local"
          port: 5432
          database: "ente_db"
          user: "ente"
          existingSecret:
            enabled: true
            secretName: "ente-postgres-app"
            passwordKey: "password"
  destination:
    server: https://kubernetes.default.svc
    namespace: ente
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    #automated:
    #  prune: true
    #  selfHeal: true
