---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ente-credentials
  namespace: ente
spec:
  encryptedData:
    credentials.yaml: AgARrQc/RuBOYkCfkXMBrX0Jfm1vEGv7Arv6LrSo60XMpIQjdtZ7IRWC4k1RYAgVQuPNrgf/3mPWBeIW1Jmw41ZZDDMyDrxtnE0qcbhVuJgZSiq+CH8C2y67OY4rvJzQZJx9esxPfLQ4ANBo2h+mLm2dZh/dGJHCUkzgyhYmZ7VvvbmtYJAfsc1Ci7oaG83KRga38vh4eYxidueJ07l/MAYCWe6w4OTB2pO+yKw5FrJusVWZiDoaU9y2XFpTUS/Z4uGXGB5CQ/KAa96IVIlAuzmy50VqBZ9WVOhoG4QOrtWAW6jpwcRJSCjOHVAA0GXBx6dDGd5EkxXVzgpdw44TnlLUo90EvJJyHWzVWRGZAHbrjxgvw0mTR3HgGQXXv2vYLM7Ptp+TP7XtbFNFg15zo65R5s91Mvm4FvuuiwU3J4ARqtJATgr6FPyCvKCRzOrF6byszF8KKSXKajzAzPlBrbss/idJ2XbBFWt0IVLLSPvw7FYAaYtAmO3pIvSXtlADKbQrFoOlvB2AgPxbPvlbL2eUh+5F6H6iC5AXvOgsCo74fCkV8bpUYH7R3ZFxTRUSKF83zEvaV5gn71uKxwGFBuXUAo6G+99uIOFmA0hl7uA3rtHz8MIiz/nWdnF8WLdDNBVKSD1rQ7YQ1a1nBNvQGCsL0ztTWCDjTAh++UteuWNWmsaWBPBSy3+RA38cge6a+iMsukrbidnj0n6dChqYDfLI2Xw+ykQqAIU4UgPyouohWY3UxkVBRxCt6HxZ9nM5qFWJfmvj9QvfDAQgL1z6JI56iXdD9SnaAvXVBTJ5xhUKQ9DKb2d5wpy8DYFaMu79zjSj7ZL32iYA2QCF9OVJuWlZWGiRRkrZQybwTzBVj0rKa5XxICMUmVXYjnGiEBsI5EpnMK0F9XXsllcz5m3Z8qjLjTrGjDwY5dQHAlUrkhu2xGZtdjSnopUMOhysbukhCUdy6XK/DziCNEP89kcs+HnjKrjRHH9BquI8xVxH9LmzTVX4rSTdAPnIeqBTIqBrzmr1bcOsEM3acQKe+KEESgv7XI9Jepki+jdbbHprQ2GBpHJC9JpiG4g3Jx4kIoVbprBe9x8B7g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ente-credentials
      namespace: ente
    type: Opaque
