apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spire
  namespace: spire-mgmt
spec:
  interval: 5m
  chart:
    spec:
      chart: spire
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: spire-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    global:
      openshift: false
      spire:
        recommendations:
          enabled: true
        namespaces:
          create: true
        ingressControllerType: ""
        clusterName: spife-cluster
        trustDomain: akna.lan
        caSubject:
          country: PL
          organization: AknaLab
          commonName: akna.lan
    server:
      replicas: 1
      logLevel: DEBUG
    agent:
      replicas: 1
      logLevel: DEBUG
    database:
      type: postgres
      host: my-postgres-host
      port: 5432
      user: spire
      passwordSecret: spire-db-password

