apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: openbao-backend-tls
  namespace: openbao
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: openbao-ui
      sectionName: https
  validation:
    hostname: openbao-ui.openbao.svc.cluster.local
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: openbao-ca
