apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: openbao-config
  namespace: tofu-runners
spec:
  interval: 5m
  approvePlan: auto
  path: ./03-flux-apps/14.openbao/tofu
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  vars:
    - name: openbao_address
      value: https://openbao-active.openbao.svc:8200
    - name: external_secrets_service_account
      value: external-secrets
    - name: external_secrets_namespace
      value: external-secrets
  backendConfig:
    inClusterConfig: true
    secretSuffix: openbao-config
    labels:
      app.kubernetes.io/name: openbao
