apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: openbao-config
  namespace: tofu-runners
spec:
  interval: 5m
  approvePlan: auto
  path: ./openbao
  branchPlanner:
    enablePathScope: true
  plan:
    lock: false
  tfVarsFiles:
    - ./openbao/config/prod.tfvars
  sourceRef:
    kind: GitRepository
    name: homelab-infra
    namespace: flux-system
  backendConfig:
    inClusterConfig: true
    secretSuffix: openbao-config
    labels:
      app.kubernetes.io/name: openbao
